[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "simple_neural_mpc"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
env = { PYTHONPATH = ".:$PYTHONPATH"}

[tasks]
build-acados = "cd external/acados && mkdir -p build && cd build && cmake -DACADOS_WITH_QPOASES=ON -DACADOS_WITH_OSQP=ON .. && make -j8"
fbl = "python simple_neural_mpc/scripts/fbl_main.py"
mpc_dyn_casadi = "python simple_neural_mpc/scripts/mpc_dyn_casadi_main.py"
mpc_kin_casadi = "python simple_neural_mpc/scripts/mpc_kin_casadi_main.py"
mpc_kin_acados = "python simple_neural_mpc/scripts/mpc_kin_acados_main.py"
postinstall = "pip install -r external/l4casadi/requirements_build.txt && pip install -e external/l4casadi --no-build-isolation"

[dependencies]
python = "==3.11"
matplotlib = ">=3.9.2,<4"
omegaconf = ">=2.3.0,<3"
pyyaml = ">=6.0.2,<7"
scipy = ">=1.14.1,<2"

[pypi-dependencies]
acados_template = {path = "external/acados/interfaces/acados_template", editable = true}
pyqt5 = "*"
torch = "*"
setuptools = ">=75.6.0, <76"
casadi = "==3.6.4"
simple_neural_mpc = { path = ".", editable = true}
