# prediction horizon
dt: 0.01
horizon: 100
color: 'red'

# weights for the cost function
cost_weights:
  ex: 10
  ey: 0.5
  F_l: 0.01
  F_r: 0.01

# input constraints
input_constraints:
  F_l_min: -100
  F_l_max: 100
  F_r_min: -100
  F_r_max: 100

# state constraints
state_constraints:
  x_min: -10
  x_max: 10
  y_min: -10
  y_max: 10
  psi_min: -0.3
  psi_max: 0.3
  